name: Build/release
# Trigger: On push
on:
    push:
        tags:
            - '**'
# Trigger: On created
# on:
#   release:
#     types:
#       - created

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, windows-latest] # ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@master
              with:
                  node-version: 16
            - name: install dependencies
              run: yarn install --production=true
            - name: publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: yarn run publish
