name: Deploy
# Trigger: On push
on:
    push:
        tags:
            - '**'
jobs:
    build-and-publish:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install packages
              run: npm install

            - name: Publish packages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_ENV: 'production'
              run: npm run publish
