name: Deploy
# Trigger: On push
on:
    push:
        tags:
            - '**'
jobs:
    build-and-publish:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install packages
              run: npm install

            # Generate the changelog
            - name: Generate Changelog
              run: |
                  npm install github-changelog-generator
                  npx github-changelog-generator
              working-directory: ${{ github.workspace }}

            # Extract changelog content and update workflow or release notes
            - name: Update Changelog in Workflow
              run: |
                  changelog=$(cat CHANGELOG.md)
                  sed -i "s#{{changelog}}#$changelog#" .github/workflows/main.yml
              working-directory: ${{ github.workspace }}

            - name: Publish packages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_ENV: 'production'
              run: npm run publish
